/**
 * Resynchronise Postgres identity sequences after migrations.
 *
 * Several migrations follow SQLite's rebuild-and-copy idiom: create a new
 * table, INSERT ... SELECT the old rows including their "id", then swap. With
 * a GENERATED BY DEFAULT identity column that insert succeeds, but Postgres
 * does not advance the underlying sequence for explicitly supplied values — so
 * the next insert reuses id 1 and fails on the primary key.
 *
 * SQLite has no equivalent problem, which is why the migrations do not account
 * for it. This runs once at boot, after migrations, and is cheap and
 * idempotent: for every identity column it sets the sequence to the highest id
 * present.
 */
import { DatabaseType } from '../shared/enums/databaseType';
import type { DatabaseAdapter } from '../shared/types/DatabaseAdapter';

type IdentityColumn = { table_name: string; column_name: string };

export const resyncIdentitySequences = async (db: DatabaseAdapter): Promise<number> => {
  if (db.type !== DatabaseType.postgre) return 0;

  const columns = await db.all<IdentityColumn>(
    `SELECT table_name, column_name
       FROM information_schema.columns
      WHERE table_schema = 'public'
        AND is_identity = 'YES'`
  );

  let resynced = 0;

  for (const { table_name, column_name } of columns) {
    // Identifiers come from information_schema, not from user input, but they
    // still cannot be bound as parameters — quote them so a table named like a
    // keyword cannot break the statement.
    const table = `"${table_name.replace(/"/g, '""')}"`;
    const column = `"${column_name.replace(/"/g, '""')}"`;

    // setval(..., false) on an empty table leaves the sequence at 1 so the
    // first insert is 1 rather than 2.
    await db.run(
      `SELECT setval(
         pg_get_serial_sequence('${table}', '${column_name.replace(/'/g, "''")}'),
         COALESCE((SELECT MAX(${column}) FROM ${table}), 0) + 1,
         false
       )`
    );
    resynced += 1;
  }

  return resynced;
};
